#!/bin/bash
zx
# force depend
command -v yt-dlp >/dev/null || { echo "yt-dlp not found"; exit 1; }
command -v convert >/dev/null || { echo "ImageMagick (convert) not found"; exit 1; }
command -v metaflac >/dev/null || { echo "metaflac not found"; exit 1; }

workdir=$(mktemp -d)


# download
yt-dlp -f bestaudio --extract-audio --audio-format flac \
  --embed-metadata --add-metadata \
  --write-thumbnail --output "$workdir/%(artist)s - %(title)s.%(ext)s" "$@"

# locate working path
flac_file=$(find "$workdir" -type f -name "*.flac" | head -n 1)
thumb_file=$(find "$workdir" -type f \( -iname "*.jpg" -o -iname "*.webp" \) | head -n 1)

# web to jpg
if [[ "$thumb_file" == *.webp ]]; then
    new_thumb="${thumb_file%.webp}.jpg"
    magick "$thumb_file" "$new_thumb"
    thumb_file="$new_thumb"
fi

# album style crop
cropped_thumb="$workdir/cropped.jpg"
magick "$thumb_file" -gravity center -crop 1:1 +repage "$cropped_thumb"


# emeb cropped into flac
metaflac --remove --block-type=PICTURE "$flac_file"
metaflac --import-picture-from="$cropped_thumb" "$flac_file"




#exit
mv "$flac_file" "$HOME/Music/"
rm -rf "$workdir"


printf '\nDownloaded: %s\n' "$(basename "$flac_file")"

sleep 0.1
stty sane 2>/dev/null
tput cnorm 2>/dev/null
printf '\n'

exit 0
